services:
  personalsite:
    image: nginx
    container_name: personalsite
    volumes:
      - ./public:/sites:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 3002:80

networks:
  proxy:
    external: true